"""Team composition contracts (hermetic Hyperplan + Security Research produce).

Hyperplan V1 and Security Research V1 (contract + hermetic result production +
shared composition task driver admission/collection + composition lane worker
protocol claim/submit) live here. Automatic worker/pane/Jobs/provider execution
remains out of scope (``execution_supported=false``).
"""

from __future__ import annotations

from omg_cli.team.compositions.hyperplan import (
    HYPERPLAN_DECISION_KIND,
    HYPERPLAN_KIND,
    HYPERPLAN_RESULT_BUNDLE_KIND,
    HYPERPLAN_SCHEMA_VERSION,
    HyperplanError,
    admit_hyperplan_tasks_v1,
    claim_hyperplan_lane_v1,
    collect_hyperplan_tasks_v1,
    compile_hyperplan_decision_v1,
    compile_hyperplan_v1,
    hyperplan_decision_path,
    hyperplan_manifest_path,
    hyperplan_result_bundle_path,
    load_hyperplan_manifest,
    materialize_hyperplan_v1,
    parse_hyperplan_spec_v1,
    produce_hyperplan_decision_v1,
    submit_hyperplan_lane_result_v1,
    validate_hyperplan_decision_v1,
)
from omg_cli.team.compositions.security_research import (
    SECURITY_RESEARCH_KIND,
    SECURITY_RESEARCH_REPORT_KIND,
    SECURITY_RESEARCH_RESULT_BUNDLE_KIND,
    SECURITY_RESEARCH_SCHEMA_VERSION,
    SecurityResearchError,
    admit_security_research_tasks_v1,
    claim_security_research_lane_v1,
    collect_security_research_tasks_v1,
    compile_security_research_report_v1,
    compile_security_research_v1,
    load_security_research_manifest,
    materialize_security_research_v1,
    parse_security_research_spec_v1,
    produce_security_research_report_v1,
    security_research_manifest_path,
    security_research_report_path,
    security_research_result_bundle_path,
    submit_security_research_lane_result_v1,
    validate_security_research_report_v1,
)

__all__ = [
    "HYPERPLAN_DECISION_KIND",
    "HYPERPLAN_KIND",
    "HYPERPLAN_RESULT_BUNDLE_KIND",
    "HYPERPLAN_SCHEMA_VERSION",
    "HyperplanError",
    "SECURITY_RESEARCH_KIND",
    "SECURITY_RESEARCH_REPORT_KIND",
    "SECURITY_RESEARCH_RESULT_BUNDLE_KIND",
    "SECURITY_RESEARCH_SCHEMA_VERSION",
    "SecurityResearchError",
    "admit_hyperplan_tasks_v1",
    "admit_security_research_tasks_v1",
    "claim_hyperplan_lane_v1",
    "claim_security_research_lane_v1",
    "collect_hyperplan_tasks_v1",
    "collect_security_research_tasks_v1",
    "compile_hyperplan_decision_v1",
    "compile_hyperplan_v1",
    "compile_security_research_report_v1",
    "compile_security_research_v1",
    "hyperplan_decision_path",
    "hyperplan_manifest_path",
    "hyperplan_result_bundle_path",
    "load_hyperplan_manifest",
    "load_security_research_manifest",
    "materialize_hyperplan_v1",
    "materialize_security_research_v1",
    "parse_hyperplan_spec_v1",
    "parse_security_research_spec_v1",
    "produce_hyperplan_decision_v1",
    "produce_security_research_report_v1",
    "security_research_manifest_path",
    "security_research_report_path",
    "security_research_result_bundle_path",
    "submit_hyperplan_lane_result_v1",
    "submit_security_research_lane_result_v1",
    "validate_hyperplan_decision_v1",
    "validate_security_research_report_v1",
]
