"""Generated parity docs stay current with the canonical inventory."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from omg_cli.contracts.parity_schema import load_json_object, validate_parity_inventory


ROOT = Path(__file__).resolve().parents[1]
MATRIX = ROOT / "docs" / "parity" / "FEATURE-MATRIX.md"
GAPS = ROOT / "docs" / "parity" / "GAPS.md"
INVENTORY = ROOT / "docs" / "parity" / "omg-parity.json"


def test_generated_feature_matrix_is_current() -> None:
    result = subprocess.run(
        [sys.executable, "scripts/generate_parity_docs.py", "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    text = MATRIX.read_text(encoding="utf-8")
    assert "GENERATED by scripts/generate_parity_docs.py" in text
    assert "bootstrapping" in text.lower()
    assert "%" not in text
    assert "✅" not in text
    assert "✓" not in text
    inventory = validate_parity_inventory(load_json_object(INVENTORY), repo_root=ROOT)
    for row in inventory["capabilities"]:
        assert f"`{row['id']}`" in text


def test_generated_gap_report_contains_open_p0s() -> None:
    result = subprocess.run(
        [sys.executable, "scripts/generate_parity_docs.py", "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    text = GAPS.read_text(encoding="utf-8")
    assert "Open P0" in text
    for issue in ("#67", "#68", "#69", "#78"):
        assert issue in text
    for gap_id in (
        "gap.antigravity.provider",
        "gap.jobs.durable",
        "gap.team.v3",
        "gap.parity.governance.remaining",
    ):
        assert gap_id in text
