"""Generated parity docs stay current with the canonical inventory."""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

from omg_cli.contracts.parity_schema import (
    SOURCE_STATUS_IDS,
    load_json_object,
    validate_parity_inventory,
)


ROOT = Path(__file__).resolve().parents[1]
PARITY_DIR = ROOT / "docs" / "parity"
MATRIX = PARITY_DIR / "FEATURE-MATRIX.md"
GAPS = PARITY_DIR / "GAPS.md"
SUMMARY = PARITY_DIR / "SUMMARY.md"
SUMMARY_ZH = PARITY_DIR / "SUMMARY.zh.md"
SUMMARY_ZH_TW = PARITY_DIR / "SUMMARY.zh-TW.md"
INVENTORY = PARITY_DIR / "omg-parity.json"
SOURCE_MATRIX_PATHS = {
    source: PARITY_DIR / f"MATRIX-{source}.md" for source in SOURCE_STATUS_IDS
}


def _load_generator():
    spec = importlib.util.spec_from_file_location(
        "generate_parity_docs",
        ROOT / "scripts" / "generate_parity_docs.py",
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _run_generate_check() -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "scripts/generate_parity_docs.py", "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )


def _assert_no_overclaim(text: str) -> None:
    assert "%" not in text
    assert "✅" not in text
    assert "✓" not in text


def test_generated_feature_matrix_is_current() -> None:
    result = _run_generate_check()
    assert result.returncode == 0, result.stderr
    text = MATRIX.read_text(encoding="utf-8")
    assert "GENERATED by scripts/generate_parity_docs.py" in text
    assert "bootstrapping" in text.lower()
    _assert_no_overclaim(text)
    inventory = validate_parity_inventory(load_json_object(INVENTORY), repo_root=ROOT)
    for row in inventory["capabilities"]:
        assert f"`{row['id']}`" in text


def test_generated_gap_report_contains_open_p0s() -> None:
    result = _run_generate_check()
    assert result.returncode == 0, result.stderr
    text = GAPS.read_text(encoding="utf-8")
    assert "Open P0" in text
    for issue in ("#67", "#68", "#69", "#78"):
        assert issue in text
    for gap_id in (
        "gap.antigravity.provider",
        "gap.jobs.durable",
        "gap.team.v3",
        "gap.parity.governance.remaining",
    ):
        assert gap_id in text


def test_generated_per_source_matrices_are_current() -> None:
    result = _run_generate_check()
    assert result.returncode == 0, result.stderr
    inventory = validate_parity_inventory(load_json_object(INVENTORY), repo_root=ROOT)
    for source, path in SOURCE_MATRIX_PATHS.items():
        assert path.is_file(), f"missing {path.name}"
        text = path.read_text(encoding="utf-8")
        assert "GENERATED by scripts/generate_parity_docs.py" in text
        assert source in text
        status = inventory["source_status"][source]
        if status == "bootstrapping":
            assert "bootstrapping" in text.lower()
        _assert_no_overclaim(text)
        rows = [
            row
            for row in inventory["capabilities"]
            if row["upstream"]["source"] == source
        ]
        for row in rows:
            assert f"`{row['id']}`" in text
            assert row["category"] in text
            assert row["gap"] in text


def test_generated_summary_omits_percent_while_bootstrapping() -> None:
    result = _run_generate_check()
    assert result.returncode == 0, result.stderr
    assert SUMMARY.is_file()
    text = SUMMARY.read_text(encoding="utf-8")
    assert "GENERATED by scripts/generate_parity_docs.py" in text
    assert "bootstrapping" in text.lower()
    _assert_no_overclaim(text)
    assert "FEATURE-MATRIX.md" in text
    assert "GAPS.md" in text
    for source in SOURCE_STATUS_IDS:
        assert f"MATRIX-{source}.md" in text


def test_parity_summary_translations_are_current() -> None:
    gen = _load_generator()
    result = _run_generate_check()
    assert result.returncode == 0, result.stderr
    inventory = validate_parity_inventory(load_json_object(INVENTORY), repo_root=ROOT)
    for path, locale in ((SUMMARY_ZH, "zh"), (SUMMARY_ZH_TW, "zh-TW")):
        assert path.is_file(), f"missing {path.name}"
        text = path.read_text(encoding="utf-8")
        assert "GENERATED by scripts/generate_parity_docs.py" in text
        assert text == gen.generate()[path]
        _assert_no_overclaim(text)
        assert str(len(inventory["capabilities"])) in text
        assert "FEATURE-MATRIX.md" in text
        assert "GAPS.md" in text
        for source in SOURCE_STATUS_IDS:
            assert f"MATRIX-{source}.md" in text
        # Locale-specific title gloss must be present (not English-only).
        if locale == "zh":
            assert "对等摘要" in text or "能力清单" in text or "清单摘要" in text
        else:
            assert "對等摘要" in text or "能力清單" in text or "清單摘要" in text


def test_parity_readme_links_generated_artifacts() -> None:
    text = (ROOT / "docs/parity/README.md").read_text(encoding="utf-8")
    for needle in (
        "FEATURE-MATRIX.md",
        "GAPS.md",
        "SUMMARY.md",
        "MATRIX-OMC.md",
        "omg-parity.json",
    ):
        assert needle in text


def test_generate_check_covers_all_parity_artifacts() -> None:
    gen = _load_generator()
    expected = {
        MATRIX,
        GAPS,
        SUMMARY,
        SUMMARY_ZH,
        SUMMARY_ZH_TW,
        *SOURCE_MATRIX_PATHS.values(),
    }
    assert {Path(p) for p in gen.GENERATED_PATHS} == expected
    result = _run_generate_check()
    assert result.returncode == 0, result.stderr
    for path in gen.GENERATED_PATHS:
        assert Path(path).is_file()
        assert "GENERATED by scripts/generate_parity_docs.py" in Path(path).read_text(
            encoding="utf-8"
        )
