"""Language-aware comment / AI-slop checker (#76).

Report-only by default. ``--fix`` only deletes ``AUTO_FIXABLE_RULES``
(banner separators and AI-meta lines), never legal/safety comments.
"""

from __future__ import annotations

import io
import json
import re
import subprocess
import tokenize
from collections.abc import Sequence
from fnmatch import fnmatch
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Final

from omg_cli.edit_hygiene.workspace import (
    WorkspacePathError,
    posix_relpath,
    read_workspace_text,
    relativize_to_root,
    write_workspace_text,
)

AUTO_FIXABLE_RULES: Final[frozenset[str]] = frozenset({"ai_meta", "banner_noise"})

_LEGAL_RE = re.compile(
    r"(?is)(?:\b(?:spdx-license-identifier|spdx-filecopyrighttext|spdx)\b"
    r"|\bcopyright\b"
    r"|\blicensed under\b"
    r"|^[ \t]*(?:[#/*]|<!--)*[ \t]*security:)"
)
_AI_META_RE = re.compile(
    r"(?is)\b(?:as an ai|ai[- ]generated|generated by (?:chatgpt|copilot|claude|"
    r"grok|gpt|an? (?:ai|llm|language model))"
    r"|this (?:function|code|file|module|helper) (?:was|is) (?:generated|written) by"
    r"|per the (?:user|task|prompt|instructions)"
    r"|as requested by the user"
    r"|i (?:added|wrote|generated) this)\b"
)
_PROMPT_RE = re.compile(
    r"(?is)\b(?:system prompt|chain of thought|hidden instruction|"
    r"ignore previous instructions|you are a helpful assistant|"
    r"let'?s think step by step|internal reasoning|copied from the prompt)\b"
)
_UNVERIFIABLE_RE = re.compile(
    r"(?is)\b(?:never fails|always works|100\s*%|guaranteed(?:ly)?|"
    r"completely safe|no bugs|trivially correct|cannot fail)\b"
)
_TODO_RE = re.compile(r"(?i)\b(?:TODO|FIXME|XXX|HACK)\b")
_TODO_OWNED_RE = re.compile(
    r"(?i)\b(?:TODO|FIXME|XXX|HACK)\s*(?:\([A-Za-z0-9._@-]+\)|@\s*[A-Za-z0-9._-]+|"
    r"#\d+|:\s*(?:owner|assignee)\s*=)"
)
_BANNER_BODY_RE = re.compile(r"^[\s#/*=\-_.~]{8,}$")
_INCREMENT_RE = re.compile(
    r"(?is)^(?:increment|decrement|increase|decrease|bump)\s+\w+$"
)
_RETURNS_BOOL_RE = re.compile(r"(?is)\breturns?\s+(true|false)\b")
_PRAGMA_RE = re.compile(r"(?i)\bomg-comments:\s*(?:ignore|disable|off)\b")
_NOQA_RE = re.compile(r"(?i)\bnoqa(?:\s*:\s*([A-Za-z0-9_., -]+))?")
_GENERATED_HEAD_RE = re.compile(r"(?is)@(?:generated|codegen)|auto-generated|do not edit")

_C_LIKE = frozenset(
    {
        ".js",
        ".jsx",
        ".ts",
        ".tsx",
        ".mjs",
        ".cjs",
        ".go",
        ".java",
        ".c",
        ".h",
        ".cc",
        ".cpp",
        ".cs",
        ".rs",
    }
)
_HASH_LIKE = frozenset({".py", ".pyi", ".sh", ".bash", ".rb", ".pl", ".yaml", ".yml"})
_SKIP_PARTS = (
    "/vendor/",
    "/node_modules/",
    "/dist/",
    "/generated/",
    "/third_party/",
)
_SKIP_SUFFIXES = (".min.js", ".min.css", ".min.mjs", ".lock")

_STOP = frozenset(
    "the a an this that we it to of for and or is are be in on as".split()
)


@dataclass(frozen=True, slots=True)
class CommentSpan:
    path: str
    start_line: int
    end_line: int
    body: str
    whole_line: bool
    documentation: bool
    next_code: str


@dataclass(frozen=True, slots=True)
class CommentFinding:
    path: str
    line: int
    end_line: int
    rule_id: str
    severity: str
    message: str
    suggested_repair: str
    auto_fixable: bool
    excerpt: str

    def to_public(self) -> dict[str, Any]:
        return {
            "path": self.path,
            "line": self.line,
            "end_line": self.end_line,
            "rule_id": self.rule_id,
            "severity": self.severity,
            "message": self.message,
            "suggested_repair": self.suggested_repair,
            "auto_fixable": self.auto_fixable,
            "excerpt": self.excerpt[:200],
        }

    def to_artifact(self) -> dict[str, Any]:
        row = self.to_public()
        row.pop("excerpt", None)
        return row


@dataclass
class CommentConfig:
    banned_patterns: list[re.Pattern[str]] = field(default_factory=list)
    suppress: list[dict[str, Any]] = field(default_factory=list)
    ignore_paths: list[str] = field(default_factory=list)


@dataclass
class CommentReport:
    findings: list[CommentFinding]
    scanned_paths: list[str]
    skipped: list[str]


class CommentCheckerError(ValueError):
    code = "E_COMMENTS"


def load_comment_config(root: Path, path: Path | None = None) -> CommentConfig:
    candidate = path if path is not None else Path(root) / ".omg" / "edit-comments.json"
    if not candidate.is_file():
        return CommentConfig()
    try:
        data = json.loads(candidate.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise CommentCheckerError("edit-comments.json is not readable JSON") from exc
    if not isinstance(data, dict):
        raise CommentCheckerError("edit-comments.json must be an object")
    patterns: list[re.Pattern[str]] = []
    raw_patterns = data.get("banned_patterns") or []
    if not isinstance(raw_patterns, list):
        raise CommentCheckerError("banned_patterns must be a list")
    for item in raw_patterns:
        if not isinstance(item, str) or not item:
            raise CommentCheckerError("banned_patterns entries must be non-empty strings")
        try:
            patterns.append(re.compile(item))
        except re.error as exc:
            raise CommentCheckerError(f"invalid banned pattern: {exc}") from exc
    suppress = data.get("suppress") or data.get("suppressions") or []
    if not isinstance(suppress, list):
        raise CommentCheckerError("suppress must be a list")
    ignore = data.get("ignore_paths") or []
    if not isinstance(ignore, list) or any(not isinstance(x, str) for x in ignore):
        raise CommentCheckerError("ignore_paths must be a string list")
    return CommentConfig(
        banned_patterns=patterns,
        suppress=[item for item in suppress if isinstance(item, dict)],
        ignore_paths=list(ignore),
    )


def looks_like_unified_diff(text: str) -> bool:
    head = text[:8000]
    return head.startswith("diff ") or head.startswith("--- ") or "\n@@ " in head


def parse_unified_diff_lines(text: str) -> dict[str, set[int]]:
    """Map workspace-relative paths to 1-based added line numbers."""

    current: str | None = None
    new_line = 0
    out: dict[str, set[int]] = {}
    for raw in text.splitlines():
        if raw.startswith("+++ "):
            rest = raw[4:].strip()
            if rest == "/dev/null":
                current = None
                continue
            if rest.startswith("b/"):
                rest = rest[2:]
            current = rest.replace("\\", "/")
            out.setdefault(current, set())
            continue
        if raw.startswith("@@"):
            match = re.match(r"^@@\s+-([0-9]+)(?:,[0-9]+)?\s+\+([0-9]+)(?:,[0-9]+)?\s+@@", raw)
            if not match:
                continue
            new_line = int(match.group(2))
            continue
        if current is None:
            continue
        if raw.startswith("+") and not raw.startswith("+++"):
            out.setdefault(current, set()).add(new_line)
            new_line += 1
        elif raw.startswith("-") and not raw.startswith("---"):
            continue
        else:
            new_line += 1
    return {path: lines for path, lines in out.items() if lines}


def git_unified_diff(root: Path, paths: Sequence[str] | None = None) -> str:
    cmd = [
        "git",
        "-C",
        str(root),
        "-c",
        "core.quotePath=false",
        "diff",
        "HEAD",
        "--unified=0",
        "--no-color",
        "--no-ext-diff",
    ]
    if paths:
        cmd.append("--")
        cmd.extend(paths)
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError as exc:
        raise CommentCheckerError("git is not available for --git-diff") from exc
    if proc.returncode != 0:
        raise CommentCheckerError("git diff failed for --git-diff")
    return proc.stdout or ""


def _is_legal(body: str) -> bool:
    return bool(_LEGAL_RE.search(body))


def _is_generated_path(rel: str) -> bool:
    posix = rel.replace("\\", "/").lstrip("/")
    wrapped = f"/{posix}"
    needle = f"/{posix}/"
    if any(part in wrapped or part in needle for part in _SKIP_PARTS):
        return True
    lower = posix.lower()
    return lower.endswith(_SKIP_SUFFIXES) or lower.endswith(".lock")


def _is_generated_text(text: str) -> bool:
    head = "\n".join(text.splitlines()[:8])
    return bool(_GENERATED_HEAD_RE.search(head))


def _tokens(text: str) -> list[str]:
    return [tok for tok in re.findall(r"[A-Za-z_][A-Za-z0-9_]*", text.lower()) if tok not in _STOP]


def _next_code_after(lines: list[str], end_line: int) -> str:
    idx = end_line
    while idx < len(lines):
        stripped = lines[idx].strip()
        if stripped and not stripped.startswith(("#", "//", "*", "/*")):
            return stripped
        idx += 1
    return ""


def _python_spans(path: str, text: str) -> list[CommentSpan]:
    lines = text.splitlines()
    spans: list[CommentSpan] = []
    try:
        tokens = list(tokenize.generate_tokens(io.StringIO(text).readline))
    except (tokenize.TokenError, IndentationError):
        return _hash_line_spans(path, text)
    for tok in tokens:
        if tok.type == tokenize.COMMENT:
            body = tok.string[1:] if tok.string.startswith("#") else tok.string
            whole = tok.start[1] == 0 or not lines[tok.start[0] - 1][: tok.start[1]].strip()
            spans.append(
                CommentSpan(
                    path=path,
                    start_line=tok.start[0],
                    end_line=tok.end[0],
                    body=body.strip(),
                    whole_line=whole,
                    documentation=False,
                    next_code=_next_code_after(lines, tok.end[0]),
                )
            )
        elif tok.type == tokenize.STRING:
            raw = tok.string.lstrip("rRuUfFbB")
            if raw.startswith(('"""', "'''")):
                inner = tok.string
                if inner[:1] in "rRuUfFbB":
                    inner = inner[1:]
                inner = inner.strip().strip("\"'")
                spans.append(
                    CommentSpan(
                        path=path,
                        start_line=tok.start[0],
                        end_line=tok.end[0],
                        body=inner.strip(),
                        whole_line=True,
                        documentation=True,
                        next_code=_next_code_after(lines, tok.end[0]),
                    )
                )
    return spans


def _hash_line_spans(path: str, text: str) -> list[CommentSpan]:
    lines = text.splitlines()
    spans: list[CommentSpan] = []
    for idx, line in enumerate(lines, start=1):
        stripped = line.lstrip()
        if stripped.startswith("#"):
            body = stripped[1:].strip()
            spans.append(
                CommentSpan(
                    path=path,
                    start_line=idx,
                    end_line=idx,
                    body=body,
                    whole_line=not line[: len(line) - len(line.lstrip())].strip()
                    and stripped.startswith("#"),
                    documentation=False,
                    next_code=_next_code_after(lines, idx),
                )
            )
    return spans


def _c_like_spans(path: str, text: str) -> list[CommentSpan]:
    lines = text.splitlines()
    spans: list[CommentSpan] = []
    i = 0
    n = len(text)
    line = 1
    col = 0
    in_s: str | None = None
    template_depth = 0
    while i < n:
        ch = text[i]
        nxt = text[i + 1] if i + 1 < n else ""
        if in_s:
            if in_s == "`" and ch == "$" and nxt == "{":
                template_depth += 1
                i += 2
                continue
            if in_s == "`" and ch == "}" and template_depth:
                template_depth -= 1
                i += 1
                continue
            if ch == "\\" and in_s != "`":
                i += 2
                continue
            if ch == in_s and not template_depth:
                in_s = None
            if ch == "\n":
                line += 1
                col = 0
            i += 1
            continue
        if ch in {'"', "'", "`"}:
            in_s = ch
            i += 1
            continue
        if ch == "/" and nxt == "/":
            start_line = line
            j = i + 2
            while j < n and text[j] != "\n":
                j += 1
            body = text[i + 2 : j].strip()
            whole = col == 0 or not text[i - col : i].strip()
            spans.append(
                CommentSpan(
                    path=path,
                    start_line=start_line,
                    end_line=start_line,
                    body=body,
                    whole_line=whole,
                    documentation=body.startswith(("/", "!")),
                    next_code=_next_code_after(lines, start_line),
                )
            )
            i = j
            continue
        if ch == "/" and nxt == "*":
            start_line = line
            j = i + 2
            while j + 1 < n and not (text[j] == "*" and text[j + 1] == "/"):
                if text[j] == "\n":
                    line += 1
                j += 1
            end_line = line
            body = text[i + 2 : j].strip()
            if j + 1 < n:
                j += 2
            spans.append(
                CommentSpan(
                    path=path,
                    start_line=start_line,
                    end_line=end_line,
                    body=body,
                    whole_line=col == 0,
                    documentation=False,
                    next_code=_next_code_after(lines, end_line),
                )
            )
            i = j
            continue
        if ch == "\n":
            line += 1
            col = 0
            i += 1
            continue
        col += 1
        i += 1
    return spans


def extract_comment_spans(path: str, text: str) -> list[CommentSpan]:
    ext = Path(path).suffix.lower()
    if ext in {".py", ".pyi"}:
        return _python_spans(path, text)
    if ext in _C_LIKE:
        return _c_like_spans(path, text)
    if ext in _HASH_LIKE:
        return _hash_line_spans(path, text)
    if ext in _C_LIKE | _HASH_LIKE:
        return _hash_line_spans(path, text)
    return _python_spans(path, text) if ext == "" else _hash_line_spans(path, text)


def _suppressed(span: CommentSpan, config: CommentConfig, rule_id: str) -> bool:
    blob = span.body
    if _PRAGMA_RE.search(blob):
        return True
    noqa = _NOQA_RE.search(blob)
    if noqa:
        listed = (noqa.group(1) or "").replace(",", " ")
        names = {item.strip() for item in listed.split() if item.strip()}
        if not names or rule_id in names:
            return True
    for item in config.suppress:
        path_pat = str(item.get("path") or "*")
        rule = str(item.get("rule") or item.get("rule_id") or "")
        line = item.get("line")
        if not fnmatch(span.path, path_pat):
            continue
        if rule and rule != rule_id:
            continue
        if line is not None and int(line) != span.start_line:
            continue
        return True
    return False


def _finding(
    span: CommentSpan,
    rule_id: str,
    severity: str,
    message: str,
    repair: str,
) -> CommentFinding:
    return CommentFinding(
        path=span.path,
        line=span.start_line,
        end_line=span.end_line,
        rule_id=rule_id,
        severity=severity,
        message=message,
        suggested_repair=repair,
        auto_fixable=rule_id in AUTO_FIXABLE_RULES,
        excerpt=span.body[:200],
    )


def _evaluate_span(span: CommentSpan, config: CommentConfig) -> list[CommentFinding]:
    if _is_legal(span.body):
        return []
    found: list[CommentFinding] = []

    def add(rule_id: str, severity: str, message: str, repair: str) -> None:
        if _suppressed(span, config, rule_id):
            return
        found.append(_finding(span, rule_id, severity, message, repair))

    if _AI_META_RE.search(span.body):
        add(
            "ai_meta",
            "warning",
            "AI/task meta-commentary does not belong in source comments",
            "Delete the AI/task meta-commentary; keep only behavior-relevant comments",
        )
    if _PROMPT_RE.search(span.body):
        add(
            "prompt_leak",
            "warning",
            "Comment looks like copied prompt or internal reasoning",
            "Remove prompt/reasoning text from the comment",
        )
    if _UNVERIFIABLE_RE.search(span.body):
        add(
            "unverifiable_claim",
            "warning",
            "Comment makes an unverifiable absolute claim",
            "Qualify or remove the unverifiable claim",
        )
    compact = re.sub(r"[\s#/*]+", "", span.body)
    if span.whole_line and (
        _BANNER_BODY_RE.match(span.body) or (len(compact) >= 8 and set(compact) <= set("=-_.~"))
    ):
        add(
            "banner_noise",
            "info",
            "Banner/separator comment is noise",
            "Delete the banner/separator comment",
        )
    if _TODO_RE.search(span.body) and not _TODO_OWNED_RE.search(span.body):
        add(
            "stale_todo",
            "info",
            "TODO/FIXME lacks ownership or issue context",
            "Add an owner, issue id, or delete the stale TODO",
        )
    if not span.documentation:
        body_tokens = _tokens(span.body)
        code_tokens = _tokens(span.next_code)
        if (
            len(body_tokens) >= 2
            and code_tokens
            and set(body_tokens) <= set(code_tokens)
        ):
            add(
                "redundant_narration",
                "info",
                "Comment restates nearby code without adding context",
                "Delete the redundant narration or replace it with why/constraints",
            )
        elif _INCREMENT_RE.match(span.body.strip()):
            add(
                "redundant_narration",
                "info",
                "Comment restates a trivial increment/decrement",
                "Delete the redundant narration",
            )
        bool_hit = _RETURNS_BOOL_RE.search(span.body)
        if bool_hit:
            claimed = bool_hit.group(1).lower()
            nxt = span.next_code.lower()
            opposite = "false" if claimed == "true" else "true"
            if re.search(rf"\breturn\s+{opposite}\b", nxt):
                add(
                    "inconsistent_with_code",
                    "warning",
                    "Comment disagrees with the nearby return value",
                    "Update the comment to match the code, or fix the code",
                )
    for pattern in config.banned_patterns:
        if pattern.search(span.body):
            add(
                "banned_pattern",
                "warning",
                "Comment matches a project banned pattern",
                "Rewrite or remove the banned comment text",
            )
            break
    return found


def check_comments(
    root: Path,
    *,
    paths: Sequence[str] | None = None,
    diff_text: str | None = None,
    config: CommentConfig | None = None,
) -> CommentReport:
    cfg = config or CommentConfig()
    changed: dict[str, set[int]] | None = None
    if diff_text is not None:
        changed = parse_unified_diff_lines(diff_text)
        targets = list(paths) if paths else list(changed)
    else:
        if not paths:
            raise CommentCheckerError("require --input PATH, --git-diff, or --paths")
        targets = list(paths)
    findings: list[CommentFinding] = []
    scanned: list[str] = []
    skipped: list[str] = []
    for raw in targets:
        try:
            rel = posix_relpath(raw.replace("\\", "/")) if not Path(raw).is_absolute() else relativize_to_root(root, raw)
        except WorkspacePathError:
            skipped.append(str(raw))
            continue
        if _is_generated_path(rel) or any(fnmatch(rel, pat) for pat in cfg.ignore_paths):
            skipped.append(rel)
            continue
        try:
            text = read_workspace_text(root, rel)
        except WorkspacePathError:
            skipped.append(rel)
            continue
        if _is_generated_text(text):
            skipped.append(rel)
            continue
        scanned.append(rel)
        allowed = None if changed is None else changed.get(rel)
        if changed is not None and not allowed:
            continue
        for span in extract_comment_spans(rel, text):
            if allowed is not None:
                span_lines = set(range(span.start_line, span.end_line + 1))
                if not (span_lines & allowed):
                    continue
            findings.extend(_evaluate_span(span, cfg))
    findings.sort(key=lambda item: (item.path, item.line, item.rule_id))
    return CommentReport(findings=findings, scanned_paths=scanned, skipped=skipped)


def _comment_line_safe_to_drop(stripped: str) -> bool:
    """True when *stripped* is comment-only and safe to delete on ``--fix``.

    A closer (``*/``) must be last non-whitespace. Anything before it must
    also look like a comment; trailing code after the closer refuses the drop.
    """

    if not stripped:
        return False
    if "*/" in stripped:
        before, _, after = stripped.partition("*/")
        if after.strip():
            return False
        head = before.strip()
        if head and not (
            head.startswith("/*") or head.startswith("*") or head.startswith("//")
        ):
            return False
    return (
        stripped.startswith("/*")
        or stripped.startswith("#")
        or stripped.startswith("//")
        or stripped.startswith("*")
        or stripped.startswith("*/")
    )


def apply_comment_fixes(
    root: Path,
    report: CommentReport,
) -> list[dict[str, Any]]:
    """Delete whole-line auto-fixable comments. Never touches legal comments."""

    by_path: dict[str, list[CommentFinding]] = {}
    for item in report.findings:
        if item.rule_id not in AUTO_FIXABLE_RULES or not item.auto_fixable:
            continue
        by_path.setdefault(item.path, []).append(item)
    applied: list[dict[str, Any]] = []
    for rel, items in by_path.items():
        text = read_workspace_text(root, rel)
        lines = text.splitlines(keepends=True)
        drop: set[int] = set()
        for item in items:
            if item.line < 1 or item.end_line > len(lines):
                continue
            # Conservative: only drop when every line in the span is a comment line.
            ok = True
            for lineno in range(item.line, item.end_line + 1):
                if not _comment_line_safe_to_drop(lines[lineno - 1].lstrip()):
                    ok = False
                    break
            if not ok:
                continue
            if _is_legal("".join(lines[item.line - 1 : item.end_line])):
                continue
            drop.update(range(item.line, item.end_line + 1))
        if not drop:
            continue
        new_lines = [line for idx, line in enumerate(lines, start=1) if idx not in drop]
        write_workspace_text(root, rel, "".join(new_lines))
        applied.append({"path": rel, "removed_lines": sorted(drop)})
    return applied
