"""Cross-session resume routing + RESUME.md workspace side-effect (research R2).

Grok Stop is passive — we cannot veto chat end. Continuity uses:
1. ``omg resume`` smart routing from active / named run
2. SessionStart writing ``.omg/state/RESUME.md`` (one-shot pack)
3. Louder context pack text for agents (status + next command)

CLI owns write/clear of RESUME.md; agents only read it.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from omg_cli.state import load_active_run, load_run, load_run_view

TERMINAL_STATUSES = frozenset({"cancelled", "completed", "failed", "verified"})

RESUME_REL = Path(".omg") / "state" / "RESUME.md"


class ResumeError(ValueError):
    """No resumable run or invalid resume request."""


def resume_md_path(root: Path) -> Path:
    return Path(root) / RESUME_REL


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _is_terminal(status: dict[str, Any]) -> bool:
    st = str(status.get("status") or "").lower()
    if st in TERMINAL_STATUSES:
        return True
    if status.get("verified") is True:
        return True
    return False


def resolve_run(root: Path, run_id: str | None = None) -> dict[str, Any] | None:
    """Load active or named run status; None if missing."""
    root = Path(root)
    if run_id:
        return load_run(root, run_id)
    return load_active_run(root)


def recommend_commands(status: dict[str, Any]) -> list[str]:
    """Return ordered shell commands to continue this run (print-only safe)."""
    rid = str(status.get("run_id") or "")
    mode = str(status.get("mode") or "").lower()
    stage = str(status.get("stage") or status.get("phase") or "")
    cmds: list[str] = []

    if mode == "pipeline":
        cmds.append(f"omg pipeline --resume {rid}")
    elif mode == "ralph":
        cmds.append(f"omg ralph --resume {rid}")
        sid = status.get("grok_session_id")
        if isinstance(sid, str) and sid.strip():
            cmds.append(f"grok --resume {sid.strip()}")
    elif mode == "autopilot":
        cmds.append(f"omg autopilot status --run {rid}")
        if stage:
            cmds.append(
                f"# continue playbook phase={stage!r}; "
                f"omg autopilot transition --run {rid} --phase <next>"
            )
        cmds.append(f"omg state --run {rid} --human")
    elif mode == "ulw":
        cmds.append(f"omg state --run {rid} --human")
        cmds.append(f"# re-run workers or: omg integrate --run {rid}")
    elif mode == "ralplan":
        cmds.append(f"omg ralplan --resume {rid}" if False else f"omg state --run {rid}")
        cmds.append(f"# ralplan: re-invoke omg ralplan with same goal if unfinished")
    elif mode in {"interview", "deep-interview"}:
        rc = status.get("resume_command")
        if isinstance(rc, str) and rc.strip():
            cmds.append(rc.strip())
        else:
            cmds.append(f"omg interview status --run {rid}")
    else:
        cmds.append(f"omg state --run {rid} --human")
        if mode:
            cmds.append(f"# mode={mode!r} stage={stage!r} — re-invoke matching skill")

    cmds.append(f"omg resume --clear  # after successfully continuing")
    return cmds


def build_resume_pack(root: Path, run_id: str | None = None) -> dict[str, Any]:
    """Build louder context pack for RESUME.md / agent bootstrap."""
    root = Path(root)
    status = resolve_run(root, run_id)
    if status is None:
        return {
            "ok": False,
            "reason": "no_active_run" if not run_id else "run_not_found",
            "run_id": run_id,
            "generated_at": _utc_now(),
        }

    rid = str(status.get("run_id") or run_id or "")
    view = load_run_view(root, rid) or status
    terminal = _is_terminal(status)
    pack: dict[str, Any] = {
        "ok": True,
        "generated_at": _utc_now(),
        "run_id": rid,
        "mode": status.get("mode"),
        "status": status.get("status"),
        "stage": status.get("stage") or status.get("phase"),
        "goal": status.get("goal") or status.get("task"),
        "verified": bool(status.get("verified")),
        "terminal": terminal,
        "resumable": not terminal,
        "grok_session_id": status.get("grok_session_id"),
        "commands": [] if terminal else recommend_commands(status),
        "view_keys": sorted(k for k in view.keys() if k not in {"goal", "task"}),
    }
    if terminal:
        pack["reason"] = "run_terminal"
        pack["hint"] = "Run is terminal; no omg resume re-entry. Start a new run if needed."
    return pack


def render_resume_md(pack: dict[str, Any]) -> str:
    """Markdown one-shot pack for agents (keep short — compaction safety)."""
    lines = [
        "# OMG RESUME (one-shot)",
        "",
        "> Generated by SessionStart / `omg resume`. **Read once**, then continue via CLI.",
        "> After you successfully resume work, run `omg resume --clear` (or let CLI clear).",
        "",
        f"- generated_at: `{pack.get('generated_at')}`",
    ]
    if not pack.get("ok"):
        lines.extend(
            [
                f"- ok: false",
                f"- reason: `{pack.get('reason')}`",
                "",
                "No active non-terminal run. Do not invent resume state.",
                "",
            ]
        )
        return "\n".join(lines)

    lines.extend(
        [
            f"- run_id: `{pack.get('run_id')}`",
            f"- mode: `{pack.get('mode')}`",
            f"- status: `{pack.get('status')}`",
            f"- stage: `{pack.get('stage')}`",
            f"- verified: `{pack.get('verified')}`",
            f"- terminal: `{pack.get('terminal')}`",
            f"- resumable: `{pack.get('resumable')}`",
        ]
    )
    goal = pack.get("goal")
    if goal:
        g = str(goal).strip().replace("\n", " ")
        if len(g) > 240:
            g = g[:237] + "..."
        lines.append(f"- goal: {g}")
    sid = pack.get("grok_session_id")
    if sid:
        lines.append(f"- grok_session_id: `{sid}`")

    lines.extend(["", "## Next commands", ""])
    cmds = pack.get("commands") or []
    if not cmds:
        lines.append(pack.get("hint") or "_none_")
    else:
        lines.append("```bash")
        for c in cmds:
            lines.append(str(c))
        lines.append("```")

    lines.extend(
        [
            "",
            "## Agent rules",
            "",
            "1. If `resumable: true`, **do not** start a conflicting new run; route via commands above.",
            "2. Prefer `omg resume` / mode CLI over free-form re-implementation.",
            "3. Never write `passes`/`verified` yourself.",
            "4. After continuing successfully: `omg resume --clear`.",
            "",
        ]
    )
    return "\n".join(lines)


def write_resume_md(root: Path, run_id: str | None = None) -> Path | None:
    """Write RESUME.md when a run exists (including terminal with explanation).

    Returns path written, or None if no run at all.
    """
    root = Path(root)
    pack = build_resume_pack(root, run_id)
    if not pack.get("ok") and pack.get("reason") in {"no_active_run", "run_not_found"}:
        # Still write a short "no active" pack so agents stop guessing.
        path = resume_md_path(root)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render_resume_md(pack), encoding="utf-8")
        return path
    path = resume_md_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_resume_md(pack), encoding="utf-8")
    return path


def clear_resume_md(root: Path) -> bool:
    """Delete RESUME.md if present. Returns True if removed."""
    path = resume_md_path(root)
    if path.is_file():
        path.unlink()
        return True
    return False


def route_resume(
    root: Path,
    *,
    run_id: str | None = None,
    write_md: bool = True,
    as_json: bool = False,
) -> tuple[int, dict[str, Any]]:
    """Primary `omg resume` entry: pack + optional RESUME.md write.

    Exit codes: 0 ok/resumable or terminal explained; 1 missing run; 2 terminal
    when strict? We use 0 for terminal with message (idempotent), 1 for missing.
    """
    pack = build_resume_pack(root, run_id)
    if write_md:
        write_resume_md(root, run_id)
        pack["resume_md"] = str(resume_md_path(root))

    if not pack.get("ok"):
        return 1, pack
    if pack.get("terminal"):
        return 0, pack
    return 0, pack


def format_pack_human(pack: dict[str, Any]) -> str:
    return render_resume_md(pack)


def format_pack_json(pack: dict[str, Any]) -> str:
    return json.dumps(pack, indent=2, ensure_ascii=False) + "\n"


__all__ = [
    "ResumeError",
    "TERMINAL_STATUSES",
    "build_resume_pack",
    "clear_resume_md",
    "format_pack_human",
    "format_pack_json",
    "recommend_commands",
    "render_resume_md",
    "resolve_run",
    "resume_md_path",
    "route_resume",
    "write_resume_md",
]
