#!/usr/bin/env python3
"""Generate FEATURE-MATRIX.md, GAPS.md, per-source matrices, SUMMARY (+ zh/zh-TW),
and the managed inventory snapshot block inside docs/parity/README.md.
"""

from __future__ import annotations

import argparse
import os
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from omg_cli.contracts.parity_schema import (  # noqa: E402
    HOST_BASELINE_PIN_ID,
    SOURCE_STATUS_IDS,
    UPSTREAM_PIN_IDS,
    claim_marker_for_capability,
    inventory_completion_claims_allowed,
    load_json_object,
    max_runtime_maturity,
    validate_parity_inventory,
)
from omg_cli.contracts.state_schemas import ContractValidationError  # noqa: E402


INVENTORY_PATH = ROOT / "docs/parity/omg-parity.json"
MATRIX_PATH = ROOT / "docs/parity/FEATURE-MATRIX.md"
GAPS_PATH = ROOT / "docs/parity/GAPS.md"
SUMMARY_PATH = ROOT / "docs/parity/SUMMARY.md"
SUMMARY_ZH_PATH = ROOT / "docs/parity/SUMMARY.zh.md"
SUMMARY_ZH_TW_PATH = ROOT / "docs/parity/SUMMARY.zh-TW.md"
README_PATH = ROOT / "docs/parity/README.md"
SOURCE_MATRIX_PATHS = {
    source: ROOT / "docs/parity" / f"MATRIX-{source}.md" for source in SOURCE_STATUS_IDS
}

GENERATED_PATHS = [
    MATRIX_PATH,
    GAPS_PATH,
    SUMMARY_PATH,
    SUMMARY_ZH_PATH,
    SUMMARY_ZH_TW_PATH,
    *[SOURCE_MATRIX_PATHS[source] for source in SOURCE_STATUS_IDS],
]

# Hand-authored files with exactly one managed interior between ownership markers.
MANAGED_BLOCK_PATHS = [
    README_PATH,
]

PARITY_README_SNAPSHOT_BEGIN = (
    "<!-- BEGIN GENERATED PARITY INVENTORY SNAPSHOT -->"
)
PARITY_README_SNAPSHOT_END = (
    "<!-- END GENERATED PARITY INVENTORY SNAPSHOT -->"
)

_GENERATED_BANNER = (
    "<!-- GENERATED by scripts/generate_parity_docs.py — do not edit by hand -->"
)

HISTORICAL_BANNER_MARKER = "HISTORICAL / NON-AUTHORITATIVE"

_PARITY_DOCS = ROOT / "docs/parity"
_RESEARCH_DIR = ROOT / "docs/research"
_COUNCIL_DIR = _RESEARCH_DIR / "omc-parity-council"


def _parity_rel_from(path: Path) -> str:
    """Relative path from ``path``'s directory to ``docs/parity/`` (posix)."""
    return Path(os.path.relpath(str(_PARITY_DOCS), str(path.parent))).as_posix()


def historical_banner_targets() -> list[tuple[Path, str]]:
    """Historical research docs that must carry the NON-AUTHORITATIVE banner.

    Covers core parity matrix, research README, and every ``*.md`` under
    ``docs/research/omc-parity-council/`` (recursive).
    """
    targets: list[tuple[Path, str]] = [
        (_RESEARCH_DIR / "core-parity-matrix-2026-07-20.md", "../parity"),
        (_RESEARCH_DIR / "README.md", "../parity"),
    ]
    if _COUNCIL_DIR.is_dir():
        for path in sorted(_COUNCIL_DIR.rglob("*.md")):
            targets.append((path, _parity_rel_from(path)))
    return targets


# Back-compat alias for tests / importers that expect a module-level list.
HISTORICAL_BANNER_TARGETS = historical_banner_targets()

# Fixed gloss strings for SUMMARY translations (do not hand-maintain tables).
_SUMMARY_GLOSS = {
    "zh": {
        "title": "对等摘要",
        "inventory_status": "清单状态",
        "bootstrapping_note": (
            "> **引导中。** 下列计数仅为覆盖统计 — 不声称对等百分比。"
        ),
        "capabilities_catalogued": "已编目能力数",
        "by_category": "按类别",
        "by_source": "按来源",
        "by_peak_maturity": "按最高成熟度",
        "capabilities_suffix": "项能力",
        "generated_matrices": "生成的矩阵",
        "matrix_full": "完整能力矩阵",
        "gaps_desc": "开放与已跟踪缺口",
        "source_rows": "行",
    },
    "zh-TW": {
        "title": "對等摘要",
        "inventory_status": "清單狀態",
        "bootstrapping_note": (
            "> **引導中。** 下列計數僅為覆蓋統計 — 不聲稱對等百分比。"
        ),
        "capabilities_catalogued": "已編目能力數",
        "by_category": "依類別",
        "by_source": "依來源",
        "by_peak_maturity": "依最高成熟度",
        "capabilities_suffix": "項能力",
        "generated_matrices": "產生的矩陣",
        "matrix_full": "完整能力矩陣",
        "gaps_desc": "開放與已追蹤缺口",
        "source_rows": "列",
    },
}


def _reject_overclaim(text: str, *, complete: bool) -> str:
    if not complete and ("%" in text or "✅" in text or "✓" in text):
        raise ContractValidationError(
            "incomplete inventory cannot emit percentage or checkmark"
        )
    return text


def _maturity_cell(row: dict) -> str:
    return ", ".join(
        f"{runtime}={level}" for runtime, level in sorted(row["maturity"].items())
    )


def _marker_cell(row: dict, inventory: dict, *, complete: bool) -> str:
    marker = claim_marker_for_capability(row, inventory=inventory) or "—"
    if not complete and marker in {"✅", "✓"}:
        marker = max_runtime_maturity(row)
    return marker


def render_feature_matrix(inventory: dict) -> str:
    lines = [
        _GENERATED_BANNER,
        "",
        "# Feature matrix",
        "",
    ]
    complete = inventory_completion_claims_allowed(inventory)
    if not complete:
        lines.extend(
            [
                "> **Inventory status: bootstrapping.** Categories or sources are incomplete.",
                "> Parity percentages and green checkmarks are intentionally omitted.",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "> Inventory status: **complete**. Markers reflect claimable maturity only.",
                "",
            ]
        )

    lines.extend(
        [
            "| Capability | Category | Classification | Maturity | Marker | Issues |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for row in inventory["capabilities"]:
        marker = _marker_cell(row, inventory, complete=complete)
        issues = ", ".join(row.get("issues") or [])
        lines.append(
            f"| `{row['id']}` | {row['category']} | {row['classification']} "
            f"| {_maturity_cell(row)} | {marker} | {issues} |"
        )
    lines.append("")
    lines.append("## Category status")
    lines.append("")
    for name, status in sorted(inventory["category_status"].items()):
        lines.append(f"- `{name}`: **{status}**")
    lines.append("")
    lines.append("## Source status")
    lines.append("")
    for name in SOURCE_STATUS_IDS:
        status = inventory["source_status"][name]
        lines.append(f"- `{name}`: **{status}**")
    lines.append("")
    return _reject_overclaim("\n".join(lines), complete=complete)


def render_gaps(inventory: dict) -> str:
    complete = inventory_completion_claims_allowed(inventory)
    lines = [
        _GENERATED_BANNER,
        "",
        "# Parity gaps",
        "",
        f"Inventory status: **{inventory['inventory_status']}**.",
        "",
        "| Gap ID | Priority | Status | Issues | Capabilities | Summary |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    gaps = sorted(
        inventory.get("gaps") or [],
        key=lambda gap: (gap.get("priority", "Z"), gap.get("id", "")),
    )
    for gap in gaps:
        lines.append(
            f"| `{gap['id']}` | {gap['priority']} | {gap['status']} | "
            f"{', '.join(gap['issues'])} | "
            f"{', '.join(f'`{cap}`' for cap in gap['capability_ids'])} | "
            f"{gap['summary']} |"
        )
    lines.append("")
    open_p0 = [
        gap
        for gap in gaps
        if gap.get("status") == "open" and gap.get("priority") == "P0"
    ]
    lines.append("## Open P0")
    lines.append("")
    if not open_p0:
        lines.append("_None._")
    else:
        for gap in open_p0:
            lines.append(
                f"- `{gap['id']}` ({', '.join(gap['issues'])}): {gap['summary']}"
            )
    lines.append("")
    return _reject_overclaim("\n".join(lines), complete=complete)


def render_source_matrix(inventory: dict, source: str) -> str:
    complete = inventory_completion_claims_allowed(inventory)
    source_status = inventory["source_status"][source]
    lines = [
        _GENERATED_BANNER,
        "",
        f"# {source} parity matrix",
        "",
    ]
    lines.append(f"> Source status: **{source_status}**.")
    if not complete:
        lines.append(
            "> Inventory still incomplete overall — "
            "parity percentages and green checkmarks are intentionally omitted."
        )
    lines.append("")

    lines.extend(
        [
            "| Capability | Category | Classification | Maturity | Marker | Gap |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    rows = [
        row
        for row in inventory["capabilities"]
        if row["upstream"]["source"] == source
    ]
    if not rows:
        lines.append("| _(none)_ | — | — | — | — | — |")
    else:
        for row in rows:
            category = row["category"]
            classification = row.get("classification") or "—"
            marker = _marker_cell(row, inventory, complete=complete)
            gap = row.get("gap") or "—"
            gap_cell = gap.replace("|", "\\|")
            lines.append(
                f"| `{row['id']}` | {category} | {classification} "
                f"| {_maturity_cell(row)} | {marker} | {gap_cell} |"
            )
    lines.append("")
    return _reject_overclaim("\n".join(lines), complete=complete)


def render_summary(inventory: dict) -> str:
    complete = inventory_completion_claims_allowed(inventory)
    lines = [
        _GENERATED_BANNER,
        "",
        "# Parity summary",
        "",
        f"Inventory status: **{inventory['inventory_status']}**.",
        "",
    ]
    if not complete:
        lines.extend(
            [
                "> **Bootstrapping.** Counts below are coverage tallies only — "
                "no parity percentage is claimed.",
                "",
            ]
        )

    cap_count = len(inventory["capabilities"])
    lines.append(f"Capabilities catalogued: **{cap_count}**.")
    lines.append("")

    lines.append("## By category")
    lines.append("")
    by_category = Counter(row["category"] for row in inventory["capabilities"])
    for name, status in sorted(inventory["category_status"].items()):
        count = by_category.get(name, 0)
        lines.append(f"- `{name}`: **{status}** ({count} capabilities)")
    lines.append("")

    lines.append("## By source")
    lines.append("")
    by_source = Counter(row["upstream"]["source"] for row in inventory["capabilities"])
    for source in SOURCE_STATUS_IDS:
        status = inventory["source_status"][source]
        count = by_source.get(source, 0)
        lines.append(f"- `{source}`: **{status}** ({count} capabilities)")
    lines.append("")

    lines.append("## By peak maturity")
    lines.append("")
    by_maturity: Counter[str] = Counter()
    for row in inventory["capabilities"]:
        by_maturity[max_runtime_maturity(row)] += 1
    for level, count in sorted(by_maturity.items()):
        lines.append(f"- `{level}`: {count}")
    lines.append("")

    lines.append("## Generated matrices")
    lines.append("")
    lines.append("- [FEATURE-MATRIX.md](FEATURE-MATRIX.md) — full capability matrix")
    lines.append("- [GAPS.md](GAPS.md) — open and tracked gaps")
    for source in SOURCE_STATUS_IDS:
        lines.append(f"- [MATRIX-{source}.md](MATRIX-{source}.md) — `{source}` rows")
    lines.append("")
    return _reject_overclaim("\n".join(lines), complete=complete)


def render_summary_locale(inventory: dict, locale: str) -> str:
    """Render SUMMARY.{zh,zh-TW}.md from inventory counts + fixed gloss strings."""
    if locale not in _SUMMARY_GLOSS:
        raise ValueError(f"unsupported summary locale: {locale}")
    gloss = _SUMMARY_GLOSS[locale]
    complete = inventory_completion_claims_allowed(inventory)
    lines = [
        _GENERATED_BANNER,
        "",
        f"# {gloss['title']}",
        "",
        f"{gloss['inventory_status']}: **{inventory['inventory_status']}**.",
        "",
    ]
    if not complete:
        lines.extend([gloss["bootstrapping_note"], ""])

    cap_count = len(inventory["capabilities"])
    lines.append(f"{gloss['capabilities_catalogued']}: **{cap_count}**.")
    lines.append("")

    lines.append(f"## {gloss['by_category']}")
    lines.append("")
    by_category = Counter(row["category"] for row in inventory["capabilities"])
    for name, status in sorted(inventory["category_status"].items()):
        count = by_category.get(name, 0)
        lines.append(
            f"- `{name}`: **{status}** ({count} {gloss['capabilities_suffix']})"
        )
    lines.append("")

    lines.append(f"## {gloss['by_source']}")
    lines.append("")
    by_source = Counter(row["upstream"]["source"] for row in inventory["capabilities"])
    for source in SOURCE_STATUS_IDS:
        status = inventory["source_status"][source]
        count = by_source.get(source, 0)
        lines.append(
            f"- `{source}`: **{status}** ({count} {gloss['capabilities_suffix']})"
        )
    lines.append("")

    lines.append(f"## {gloss['by_peak_maturity']}")
    lines.append("")
    by_maturity: Counter[str] = Counter()
    for row in inventory["capabilities"]:
        by_maturity[max_runtime_maturity(row)] += 1
    for level, count in sorted(by_maturity.items()):
        lines.append(f"- `{level}`: {count}")
    lines.append("")

    lines.append(f"## {gloss['generated_matrices']}")
    lines.append("")
    lines.append(
        f"- [FEATURE-MATRIX.md](FEATURE-MATRIX.md) — {gloss['matrix_full']}"
    )
    lines.append(f"- [GAPS.md](GAPS.md) — {gloss['gaps_desc']}")
    for source in SOURCE_STATUS_IDS:
        lines.append(
            f"- [MATRIX-{source}.md](MATRIX-{source}.md) — `{source}` "
            f"{gloss['source_rows']}"
        )
    lines.append("")
    return _reject_overclaim("\n".join(lines), complete=complete)


def historical_banner_text(*, parity_rel: str) -> str:
    """Exact English NON-AUTHORITATIVE banner; ``parity_rel`` is relative to docs/parity."""
    return (
        f"> **{HISTORICAL_BANNER_MARKER}.** This document predates the v2 parity inventory.\n"
        f"> Current claimability truth: "
        f"[`docs/parity/omg-parity.json`]({parity_rel}/omg-parity.json)\n"
        f"> and generated "
        f"[`docs/parity/FEATURE-MATRIX.md`]({parity_rel}/FEATURE-MATRIX.md).\n"
        "\n"
    )


def apply_historical_banner(path: Path, *, parity_rel: str) -> bool:
    """Prepend NON-AUTHORITATIVE banner if missing. Idempotent. Returns True if written."""
    text = path.read_text(encoding="utf-8") if path.is_file() else ""
    if HISTORICAL_BANNER_MARKER in text:
        return False
    path.write_text(historical_banner_text(parity_rel=parity_rel) + text, encoding="utf-8")
    return True


def check_historical_banners() -> list[str]:
    """Return relative paths missing the NON-AUTHORITATIVE banner."""
    missing: list[str] = []
    for path, parity_rel in historical_banner_targets():
        text = path.read_text(encoding="utf-8") if path.is_file() else ""
        if HISTORICAL_BANNER_MARKER not in text:
            missing.append(path.relative_to(ROOT).as_posix())
            continue
        expected_inv = f"{parity_rel}/omg-parity.json"
        expected_matrix = f"{parity_rel}/FEATURE-MATRIX.md"
        if expected_inv not in text or expected_matrix not in text:
            missing.append(path.relative_to(ROOT).as_posix())
    return missing


def render_parity_readme_snapshot(inventory: dict) -> str:
    """Deterministic managed README interior from a validated inventory.

    Counts and statuses only — no timestamps, percentages, or checkmarks.
    Schema vocabulary tokens are Markdown code spans.
    """
    complete = inventory_completion_claims_allowed(inventory)
    open_gaps = [
        gap for gap in (inventory.get("gaps") or []) if gap.get("status") == "open"
    ]
    open_p0 = [gap for gap in open_gaps if gap.get("priority") == "P0"]
    lines = [
        _GENERATED_BANNER,
        "",
        "## Inventory snapshot",
        "",
        "Projected from the canonical inventory. Tokens below are schema vocabulary, "
        "not runtime verification claims.",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| `store_kind` | `{inventory['store_kind']}` |",
        f"| `schema_version` | `{inventory['schema_version']}` |",
        f"| `repository_id` | `{inventory['repository_id']}` |",
        f"| `ownership_manifest_id` | `{inventory['ownership_manifest_id']}` |",
        f"| `inventory_status` | `{inventory['inventory_status']}` |",
        f"| `live_evidence_max_age_days` | `{inventory['live_evidence_max_age_days']}` |",
        f"| Capabilities catalogued | {len(inventory['capabilities'])} |",
        f"| Open gaps | {len(open_gaps)} |",
        f"| Open P0 gaps | {len(open_p0)} |",
        "",
        "### Source status",
        "",
        "| Source | Status |",
        "| --- | --- |",
    ]
    for source in SOURCE_STATUS_IDS:
        status = inventory["source_status"][source]
        lines.append(f"| `{source}` | `{status}` |")
    lines.extend(
        [
            "",
            "### Category status",
            "",
            "| Category | Status |",
            "| --- | --- |",
        ]
    )
    for name, status in sorted(inventory["category_status"].items()):
        lines.append(f"| `{name}` | `{status}` |")
    lines.extend(
        [
            "",
            "### Upstream pins",
            "",
            f"`{HOST_BASELINE_PIN_ID}` is the independent Grok Build host baseline "
            "(not a parity source).",
            "",
            "| Pin | Repository | Revision | Kind |",
            "| --- | --- | --- | --- |",
        ]
    )
    pins = inventory["upstream_pins"]
    for pin_id in UPSTREAM_PIN_IDS:
        pin = pins[pin_id]
        lines.append(
            f"| `{pin_id}` | `{pin['repository']}` | `{pin['revision']}` | `{pin['kind']}` |"
        )
    maturity = " → ".join(f"`{level}`" for level in inventory["maturity_levels"])
    classifications = ", ".join(f"`{item}`" for item in inventory["classifications"])
    lines.extend(
        [
            "",
            "### Maturity levels (inventory order)",
            "",
            maturity,
            "",
            "### Classifications (inventory order)",
            "",
            classifications,
            "",
            "### Peak maturity distribution",
            "",
            "| Peak maturity | Count |",
            "| --- | --- |",
        ]
    )
    by_maturity: Counter[str] = Counter()
    for row in inventory["capabilities"]:
        by_maturity[max_runtime_maturity(row)] += 1
    for level in inventory["maturity_levels"]:
        if level in by_maturity:
            lines.append(f"| `{level}` | {by_maturity[level]} |")
    for level, count in sorted(by_maturity.items()):
        if level not in inventory["maturity_levels"]:
            lines.append(f"| `{level}` | {count} |")
    lines.append("")
    return _reject_overclaim("\n".join(lines), complete=complete)


def split_managed_block(
    text: str,
    *,
    begin: str,
    end: str,
    label: str,
) -> tuple[str, str, str]:
    """Split ``text`` into (prefix, interior, suffix) around one marker pair.

    Fail-closed on missing, duplicate, nested, or reversed markers. Never
    invents a second block.
    """
    begin_count = text.count(begin)
    end_count = text.count(end)
    if begin_count != 1 or end_count != 1:
        raise ContractValidationError(
            f"malformed managed markers in {label}: "
            f"expected exactly one begin and one end "
            f"(begin={begin_count}, end={end_count})"
        )
    begin_at = text.index(begin)
    end_at = text.index(end)
    if end_at < begin_at:
        raise ContractValidationError(
            f"malformed managed markers in {label}: end precedes begin"
        )
    interior_start = begin_at + len(begin)
    if text[interior_start : interior_start + 1] == "\n":
        interior_start += 1
    interior_end = end_at
    if interior_end > 0 and text[interior_end - 1] == "\n":
        interior_end -= 1
    prefix = text[:begin_at]
    interior = text[interior_start:interior_end]
    suffix = text[end_at + len(end) :]
    return prefix, interior, suffix


def apply_managed_block(
    text: str,
    interior: str,
    *,
    begin: str,
    end: str,
    label: str,
) -> str:
    """Replace only the bytes between ownership markers; preserve prefix/suffix."""
    prefix, _old, suffix = split_managed_block(
        text, begin=begin, end=end, label=label
    )
    body = interior if interior.endswith("\n") else interior + "\n"
    return f"{prefix}{begin}\n{body}{end}{suffix}"


def render_managed_blocks(inventory: dict) -> dict[Path, str]:
    """Expected managed interiors keyed by path (validated inventory required)."""
    return {
        README_PATH: render_parity_readme_snapshot(inventory),
    }


def generate(inventory_path: Path = INVENTORY_PATH) -> dict[Path, str]:
    inventory = validate_parity_inventory(
        load_json_object(inventory_path),
        repo_root=ROOT,
    )
    rendered: dict[Path, str] = {
        MATRIX_PATH: render_feature_matrix(inventory),
        GAPS_PATH: render_gaps(inventory),
        SUMMARY_PATH: render_summary(inventory),
        SUMMARY_ZH_PATH: render_summary_locale(inventory, "zh"),
        SUMMARY_ZH_TW_PATH: render_summary_locale(inventory, "zh-TW"),
    }
    for source in SOURCE_STATUS_IDS:
        rendered[SOURCE_MATRIX_PATHS[source]] = render_source_matrix(inventory, source)
    return rendered


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if generated docs drift from the inventory",
    )
    parser.add_argument(
        "--inventory",
        default=str(INVENTORY_PATH),
        help="parity inventory path",
    )
    args = parser.parse_args(argv)

    try:
        inventory = validate_parity_inventory(
            load_json_object(Path(args.inventory)),
            repo_root=ROOT,
        )
        rendered = generate(Path(args.inventory))
        managed = render_managed_blocks(inventory)
    except ContractValidationError as exc:
        print(f"generate_parity_docs: {exc}", file=sys.stderr)
        return 1

    if args.check:
        stale: list[str] = []
        stale_managed: list[str] = []
        marker_errors: list[str] = []
        for path in GENERATED_PATHS:
            expected = rendered[path]
            current = path.read_text(encoding="utf-8") if path.is_file() else ""
            if current != expected:
                stale.append(path.relative_to(ROOT).as_posix())
        for path in MANAGED_BLOCK_PATHS:
            rel = path.relative_to(ROOT).as_posix()
            current = path.read_text(encoding="utf-8") if path.is_file() else ""
            try:
                _prefix, interior, _suffix = split_managed_block(
                    current,
                    begin=PARITY_README_SNAPSHOT_BEGIN,
                    end=PARITY_README_SNAPSHOT_END,
                    label=rel,
                )
            except ContractValidationError as exc:
                marker_errors.append(str(exc))
                continue
            if interior.rstrip("\n") != managed[path].rstrip("\n"):
                stale_managed.append(rel)
        banner_issues = check_historical_banners()
        if stale or stale_managed or marker_errors or banner_issues:
            parts: list[str] = []
            if stale:
                parts.append(
                    "stale generated docs: " + ", ".join(stale) + "; re-run without --check"
                )
            if stale_managed:
                parts.append(
                    "stale managed artifact: "
                    + ", ".join(stale_managed)
                    + "; re-run without --check"
                )
            if marker_errors:
                parts.append("; ".join(marker_errors))
            if banner_issues:
                parts.append(
                    "missing historical banners: "
                    + ", ".join(banner_issues)
                    + "; re-run without --check"
                )
            print("generate_parity_docs: " + "; ".join(parts), file=sys.stderr)
            return 1
        print("generate_parity_docs: ok")
        return 0

    for path in GENERATED_PATHS:
        path.write_text(rendered[path], encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    for path in MANAGED_BLOCK_PATHS:
        rel = path.relative_to(ROOT).as_posix()
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        try:
            updated = apply_managed_block(
                current,
                managed[path].rstrip("\n") + "\n",
                begin=PARITY_README_SNAPSHOT_BEGIN,
                end=PARITY_README_SNAPSHOT_END,
                label=rel,
            )
        except ContractValidationError as exc:
            print(f"generate_parity_docs: {exc}", file=sys.stderr)
            return 1
        path.write_text(updated, encoding="utf-8")
        print(f"updated managed block {rel}")
    for path, parity_rel in historical_banner_targets():
        if apply_historical_banner(path, parity_rel=parity_rel):
            print(f"bannered {path.relative_to(ROOT)}")
        else:
            print(f"banner ok {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
