#!/usr/bin/env python3
"""Generate docs/parity/generated/host-*.md from the host-baseline snapshot."""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from omg_cli.contracts.parity_schema import (  # noqa: E402
    HOST_BASELINE_GENERATED_RELATIVE,
    HOST_BASELINE_SNAPSHOT_RELATIVE,
    load_json_object,
    validate_host_baseline_snapshot,
)
from omg_cli.contracts.state_schemas import ContractValidationError  # noqa: E402
from omg_cli.parity_claim_gate import (  # noqa: E402
    assert_host_generated_docs_consistent,
    assert_host_review_binds_current_content,
)

_BANNER = "<!-- GENERATED by scripts/generate_host_baseline_docs.py — do not edit by hand -->"


def render_host_baseline_md(snapshot: dict) -> str:
    lines = [
        _BANNER,
        "",
        "# Grok Build host baseline",
        "",
        "Independent **host runtime** catalogue (not an OMC/OMX/OmO/Antigravity parity source).",
        "Rows start at `catalogued` unless a later PR promotes them with deterministic or live evidence.",
        "",
        f"- Repository: `{snapshot['repository']}`",
        f"- Public commit: `{snapshot['public_commit']}`",
        f"- Source-Revision: `{snapshot['source_revision']}`",
        f"- Release: `{snapshot['release']}`",
        f"- Observed version: `{snapshot['observed_version']}`",
        f"- Platform note: {snapshot['platform']}",
        f"- Maturity floor: `{snapshot['maturity_floor']}`",
        f"- Review status: `{snapshot['review']['status']}`",
        f"- Issues: {', '.join(snapshot['issues'])}",
        "",
        "## Classification counts",
        "",
    ]
    counts = Counter(cap["classification"] for cap in snapshot["capabilities"])
    for key in ("host_owned", "consumed_downstream", "irrelevant"):
        lines.append(f"- `{key}`: {counts.get(key, 0)}")
    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- `host_owned` rows must not claim OMG `omg_paths` as implementation evidence.",
            "- `consumed_downstream` rows document host contracts OMG Team/session/jobs/MCP may adopt later.",
            "- This generated summary does **not** claim OMG has implemented host-owned UI.",
            "",
        ]
    )
    return "\n".join(lines)


def render_host_matrix_md(snapshot: dict) -> str:
    lines = [
        _BANNER,
        "",
        "# Grok Build host capability matrix",
        "",
        f"Pin `{snapshot['public_commit']}` / release `{snapshot['release']}` "
        "(catalogue-only; no live promotion in this artifact).",
        "",
        "| ID | Category | Classification | Maturity | Downstream issues | Promise |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for cap in sorted(snapshot["capabilities"], key=lambda row: row["id"]):
        issues = ", ".join(cap.get("downstream_issues") or []) or "—"
        promise = cap["promise"].replace("|", "\\|")
        lines.append(
            f"| `{cap['id']}` | {cap['category']} | `{cap['classification']}` | "
            f"`{cap['maturity']}` | {issues} | {promise} |"
        )
    lines.append("")
    return "\n".join(lines)


def generate(repo_root: Path) -> list[Path]:
    snapshot_path = repo_root / HOST_BASELINE_SNAPSHOT_RELATIVE
    snapshot = validate_host_baseline_snapshot(load_json_object(snapshot_path))
    written: list[Path] = []
    mapping = {
        HOST_BASELINE_GENERATED_RELATIVE[0]: render_host_baseline_md(snapshot),
        HOST_BASELINE_GENERATED_RELATIVE[1]: render_host_matrix_md(snapshot),
    }
    for relative, text in mapping.items():
        path = repo_root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root = args.repo_root.resolve()
    if args.check:
        snapshot = validate_host_baseline_snapshot(
            load_json_object(root / HOST_BASELINE_SNAPSHOT_RELATIVE)
        )
        expected = {
            HOST_BASELINE_GENERATED_RELATIVE[0]: render_host_baseline_md(snapshot),
            HOST_BASELINE_GENERATED_RELATIVE[1]: render_host_matrix_md(snapshot),
        }
        drift = []
        for relative, text in expected.items():
            path = root / relative
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                drift.append(relative)
        if drift:
            print("host baseline generated docs drift: " + ", ".join(drift), file=sys.stderr)
            return 1
        try:
            docs_hash = assert_host_generated_docs_consistent(
                repo_root=root, host_snapshot=snapshot
            )
            assert_host_review_binds_current_content(
                repo_root=root, snapshot=snapshot, docs_hash=docs_hash
            )
        except ContractValidationError as exc:
            print(f"host baseline review bind failed: {exc}", file=sys.stderr)
            return 1
        print("host baseline generated docs OK")
        return 0
    paths = generate(root)
    for path in paths:
        print(path.relative_to(root).as_posix())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
