#!/usr/bin/env python3
"""Generate FEATURE-MATRIX.md, GAPS.md, per-source matrices, and SUMMARY from inventory."""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from omg_cli.contracts.parity_schema import (  # noqa: E402
    SOURCE_STATUS_IDS,
    claim_marker_for_capability,
    inventory_completion_claims_allowed,
    load_json_object,
    max_runtime_maturity,
    validate_parity_inventory,
)
from omg_cli.contracts.state_schemas import ContractValidationError  # noqa: E402


INVENTORY_PATH = ROOT / "docs/parity/omg-parity.json"
MATRIX_PATH = ROOT / "docs/parity/FEATURE-MATRIX.md"
GAPS_PATH = ROOT / "docs/parity/GAPS.md"
SUMMARY_PATH = ROOT / "docs/parity/SUMMARY.md"
SOURCE_MATRIX_PATHS = {
    source: ROOT / "docs/parity" / f"MATRIX-{source}.md" for source in SOURCE_STATUS_IDS
}

GENERATED_PATHS = [
    MATRIX_PATH,
    GAPS_PATH,
    SUMMARY_PATH,
    *[SOURCE_MATRIX_PATHS[source] for source in SOURCE_STATUS_IDS],
]

_GENERATED_BANNER = (
    "<!-- GENERATED by scripts/generate_parity_docs.py — do not edit by hand -->"
)


def _reject_overclaim(text: str, *, complete: bool) -> str:
    if not complete and ("%" in text or "✅" in text or "✓" in text):
        raise ContractValidationError(
            "incomplete inventory cannot emit percentage or checkmark"
        )
    return text


def _maturity_cell(row: dict) -> str:
    return ", ".join(
        f"{runtime}={level}" for runtime, level in sorted(row["maturity"].items())
    )


def _marker_cell(row: dict, inventory: dict, *, complete: bool) -> str:
    marker = claim_marker_for_capability(row, inventory=inventory) or "—"
    if not complete and marker in {"✅", "✓"}:
        marker = max_runtime_maturity(row)
    return marker


def render_feature_matrix(inventory: dict) -> str:
    lines = [
        _GENERATED_BANNER,
        "",
        "# Feature matrix",
        "",
    ]
    complete = inventory_completion_claims_allowed(inventory)
    if not complete:
        lines.extend(
            [
                "> **Inventory status: bootstrapping.** Categories or sources are incomplete.",
                "> Parity percentages and green checkmarks are intentionally omitted.",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "> Inventory status: **complete**. Markers reflect claimable maturity only.",
                "",
            ]
        )

    lines.extend(
        [
            "| Capability | Category | Classification | Maturity | Marker | Issues |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for row in inventory["capabilities"]:
        marker = _marker_cell(row, inventory, complete=complete)
        issues = ", ".join(row.get("issues") or [])
        lines.append(
            f"| `{row['id']}` | {row['category']} | {row['classification']} "
            f"| {_maturity_cell(row)} | {marker} | {issues} |"
        )
    lines.append("")
    lines.append("## Category status")
    lines.append("")
    for name, status in sorted(inventory["category_status"].items()):
        lines.append(f"- `{name}`: **{status}**")
    lines.append("")
    lines.append("## Source status")
    lines.append("")
    for name in SOURCE_STATUS_IDS:
        status = inventory["source_status"][name]
        lines.append(f"- `{name}`: **{status}**")
    lines.append("")
    return _reject_overclaim("\n".join(lines), complete=complete)


def render_gaps(inventory: dict) -> str:
    complete = inventory_completion_claims_allowed(inventory)
    lines = [
        _GENERATED_BANNER,
        "",
        "# Parity gaps",
        "",
        f"Inventory status: **{inventory['inventory_status']}**.",
        "",
        "| Gap ID | Priority | Status | Issues | Capabilities | Summary |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    gaps = sorted(
        inventory.get("gaps") or [],
        key=lambda gap: (gap.get("priority", "Z"), gap.get("id", "")),
    )
    for gap in gaps:
        lines.append(
            f"| `{gap['id']}` | {gap['priority']} | {gap['status']} | "
            f"{', '.join(gap['issues'])} | "
            f"{', '.join(f'`{cap}`' for cap in gap['capability_ids'])} | "
            f"{gap['summary']} |"
        )
    lines.append("")
    open_p0 = [
        gap
        for gap in gaps
        if gap.get("status") == "open" and gap.get("priority") == "P0"
    ]
    lines.append("## Open P0")
    lines.append("")
    if not open_p0:
        lines.append("_None._")
    else:
        for gap in open_p0:
            lines.append(
                f"- `{gap['id']}` ({', '.join(gap['issues'])}): {gap['summary']}"
            )
    lines.append("")
    return _reject_overclaim("\n".join(lines), complete=complete)


def render_source_matrix(inventory: dict, source: str) -> str:
    complete = inventory_completion_claims_allowed(inventory)
    source_status = inventory["source_status"][source]
    lines = [
        _GENERATED_BANNER,
        "",
        f"# {source} parity matrix",
        "",
    ]
    if source_status == "bootstrapping" or not complete:
        lines.extend(
            [
                f"> **Source status: bootstrapping.** `{source}` inventory is incomplete.",
                "> Parity percentages and green checkmarks are intentionally omitted.",
                "",
            ]
        )
    else:
        lines.extend(
            [
                f"> Source status: **{source_status}**.",
                "",
            ]
        )

    lines.extend(
        [
            f"Source status: **{source_status}**.",
            "",
            "| Capability | Category | Status | Maturity | Marker | Gap |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    rows = [
        row
        for row in inventory["capabilities"]
        if row["upstream"]["source"] == source
    ]
    if not rows:
        lines.append("| _(none)_ | — | — | — | — | — |")
    else:
        for row in rows:
            category = row["category"]
            cat_status = inventory["category_status"].get(category, "bootstrapping")
            marker = _marker_cell(row, inventory, complete=complete)
            gap = row.get("gap") or "—"
            gap_cell = gap.replace("|", "\\|")
            lines.append(
                f"| `{row['id']}` | {category} | {cat_status} "
                f"| {_maturity_cell(row)} | {marker} | {gap_cell} |"
            )
    lines.append("")
    return _reject_overclaim("\n".join(lines), complete=complete)


def render_summary(inventory: dict) -> str:
    complete = inventory_completion_claims_allowed(inventory)
    lines = [
        _GENERATED_BANNER,
        "",
        "# Parity summary",
        "",
        f"Inventory status: **{inventory['inventory_status']}**.",
        "",
    ]
    if not complete:
        lines.extend(
            [
                "> **Bootstrapping.** Counts below are coverage tallies only — "
                "no parity percentage is claimed.",
                "",
            ]
        )

    cap_count = len(inventory["capabilities"])
    lines.append(f"Capabilities catalogued: **{cap_count}**.")
    lines.append("")

    lines.append("## By category")
    lines.append("")
    by_category = Counter(row["category"] for row in inventory["capabilities"])
    for name, status in sorted(inventory["category_status"].items()):
        count = by_category.get(name, 0)
        lines.append(f"- `{name}`: **{status}** ({count} capabilities)")
    lines.append("")

    lines.append("## By source")
    lines.append("")
    by_source = Counter(row["upstream"]["source"] for row in inventory["capabilities"])
    for source in SOURCE_STATUS_IDS:
        status = inventory["source_status"][source]
        count = by_source.get(source, 0)
        lines.append(f"- `{source}`: **{status}** ({count} capabilities)")
    lines.append("")

    lines.append("## By peak maturity")
    lines.append("")
    by_maturity: Counter[str] = Counter()
    for row in inventory["capabilities"]:
        by_maturity[max_runtime_maturity(row)] += 1
    for level, count in sorted(by_maturity.items()):
        lines.append(f"- `{level}`: {count}")
    lines.append("")

    lines.append("## Generated matrices")
    lines.append("")
    lines.append("- [FEATURE-MATRIX.md](FEATURE-MATRIX.md) — full capability matrix")
    lines.append("- [GAPS.md](GAPS.md) — open and tracked gaps")
    for source in SOURCE_STATUS_IDS:
        lines.append(f"- [MATRIX-{source}.md](MATRIX-{source}.md) — `{source}` rows")
    lines.append("")
    return _reject_overclaim("\n".join(lines), complete=complete)


def generate(inventory_path: Path = INVENTORY_PATH) -> dict[Path, str]:
    inventory = validate_parity_inventory(
        load_json_object(inventory_path),
        repo_root=ROOT,
    )
    rendered: dict[Path, str] = {
        MATRIX_PATH: render_feature_matrix(inventory),
        GAPS_PATH: render_gaps(inventory),
        SUMMARY_PATH: render_summary(inventory),
    }
    for source in SOURCE_STATUS_IDS:
        rendered[SOURCE_MATRIX_PATHS[source]] = render_source_matrix(inventory, source)
    return rendered


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if generated docs drift from the inventory",
    )
    parser.add_argument(
        "--inventory",
        default=str(INVENTORY_PATH),
        help="parity inventory path",
    )
    args = parser.parse_args(argv)

    try:
        rendered = generate(Path(args.inventory))
    except ContractValidationError as exc:
        print(f"generate_parity_docs: {exc}", file=sys.stderr)
        return 1

    if args.check:
        stale: list[str] = []
        for path in GENERATED_PATHS:
            expected = rendered[path]
            current = path.read_text(encoding="utf-8") if path.is_file() else ""
            if current != expected:
                stale.append(path.relative_to(ROOT).as_posix())
        if stale:
            print(
                "generate_parity_docs: stale generated docs: "
                + ", ".join(stale)
                + "; re-run without --check",
                file=sys.stderr,
            )
            return 1
        print("generate_parity_docs: ok")
        return 0

    for path in GENERATED_PATHS:
        path.write_text(rendered[path], encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
