#!/usr/bin/env python3
"""Generate FEATURE-MATRIX.md and GAPS.md from the canonical parity inventory."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from omg_cli.contracts.parity_schema import (  # noqa: E402
    claim_marker_for_capability,
    inventory_completion_claims_allowed,
    load_json_object,
    max_runtime_maturity,
    validate_parity_inventory,
)
from omg_cli.contracts.state_schemas import ContractValidationError  # noqa: E402


INVENTORY_PATH = ROOT / "docs/parity/omg-parity.json"
MATRIX_PATH = ROOT / "docs/parity/FEATURE-MATRIX.md"
GAPS_PATH = ROOT / "docs/parity/GAPS.md"


def render_feature_matrix(inventory: dict) -> str:
    lines = [
        "<!-- GENERATED by scripts/generate_parity_docs.py — do not edit by hand -->",
        "",
        "# Feature matrix",
        "",
    ]
    complete = inventory_completion_claims_allowed(inventory)
    if not complete:
        lines.extend(
            [
                "> **Inventory status: bootstrapping.** Categories are incomplete.",
                "> Parity percentages and green checkmarks are intentionally omitted.",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "> Inventory status: **complete**. Markers reflect claimable maturity only.",
                "",
            ]
        )

    lines.extend(
        [
            "| Capability | Category | Classification | Maturity | Marker | Issues |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for row in inventory["capabilities"]:
        maturity = ", ".join(
            f"{runtime}={level}" for runtime, level in sorted(row["maturity"].items())
        )
        marker = claim_marker_for_capability(row, inventory=inventory) or "—"
        # Hard ban on overclaim glyphs while bootstrapping.
        if not complete and marker in {"✅", "✓"}:
            marker = max_runtime_maturity(row)
        issues = ", ".join(row.get("issues") or [])
        lines.append(
            f"| `{row['id']}` | {row['category']} | {row['classification']} "
            f"| {maturity} | {marker} | {issues} |"
        )
    lines.append("")
    lines.append("## Category status")
    lines.append("")
    for name, status in sorted(inventory["category_status"].items()):
        lines.append(f"- `{name}`: **{status}**")
    lines.append("")
    text = "\n".join(lines)
    if not complete:
        if "%" in text or "✅" in text or "✓" in text:
            raise ContractValidationError(
                "incomplete inventory cannot emit percentage or checkmark"
            )
    return text


def render_gaps(inventory: dict) -> str:
    lines = [
        "<!-- GENERATED by scripts/generate_parity_docs.py — do not edit by hand -->",
        "",
        "# Parity gaps",
        "",
        f"Inventory status: **{inventory['inventory_status']}**.",
        "",
        "| Gap ID | Priority | Status | Issues | Capabilities | Summary |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    gaps = sorted(
        inventory.get("gaps") or [],
        key=lambda gap: (gap.get("priority", "Z"), gap.get("id", "")),
    )
    for gap in gaps:
        lines.append(
            f"| `{gap['id']}` | {gap['priority']} | {gap['status']} | "
            f"{', '.join(gap['issues'])} | "
            f"{', '.join(f'`{cap}`' for cap in gap['capability_ids'])} | "
            f"{gap['summary']} |"
        )
    lines.append("")
    open_p0 = [
        gap
        for gap in gaps
        if gap.get("status") == "open" and gap.get("priority") == "P0"
    ]
    lines.append("## Open P0")
    lines.append("")
    if not open_p0:
        lines.append("_None._")
    else:
        for gap in open_p0:
            lines.append(
                f"- `{gap['id']}` ({', '.join(gap['issues'])}): {gap['summary']}"
            )
    lines.append("")
    return "\n".join(lines)


def generate(inventory_path: Path = INVENTORY_PATH) -> tuple[str, str]:
    inventory = validate_parity_inventory(
        load_json_object(inventory_path),
        repo_root=ROOT,
    )
    return render_feature_matrix(inventory), render_gaps(inventory)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if generated docs drift from the inventory",
    )
    parser.add_argument(
        "--inventory",
        default=str(INVENTORY_PATH),
        help="parity inventory path",
    )
    args = parser.parse_args(argv)

    try:
        matrix, gaps = generate(Path(args.inventory))
    except ContractValidationError as exc:
        print(f"generate_parity_docs: {exc}", file=sys.stderr)
        return 1

    if args.check:
        current_matrix = MATRIX_PATH.read_text(encoding="utf-8") if MATRIX_PATH.is_file() else ""
        current_gaps = GAPS_PATH.read_text(encoding="utf-8") if GAPS_PATH.is_file() else ""
        if current_matrix != matrix or current_gaps != gaps:
            print(
                "generate_parity_docs: FEATURE-MATRIX.md / GAPS.md are stale; "
                "re-run without --check",
                file=sys.stderr,
            )
            return 1
        print("generate_parity_docs: ok")
        return 0

    MATRIX_PATH.write_text(matrix, encoding="utf-8")
    GAPS_PATH.write_text(gaps, encoding="utf-8")
    print(f"wrote {MATRIX_PATH.relative_to(ROOT)}")
    print(f"wrote {GAPS_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
